name: CI/CD - EC2 App Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy App to EC2
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Terraform Init
      - name: Terraform Init
        working-directory: ec2-automation/terraform
        run: terraform init

            # Run Terraform Import Script
      - name: Import existing resources into Terraform state
        run: |
          chmod +x ec2-automation/terraform/terraform-import.sh
          ec2-automation/terraform/terraform-import.sh


      # Terraform Plan
      - name: Terraform Plan
        working-directory: ec2-automation/terraform
        run: terraform plan -var-file="dev.tfvars"

      # Terraform Apply
      - name: Terraform Apply
        working-directory: ec2-automation/terraform
        run: terraform apply -auto-approve -var-file="dev.tfvars"

      # Get EC2 Instance IP
      - name: Get EC2 Instance IP
        working-directory: ec2-automation/terraform
        id: get_ip
        run: |
          echo "instance_ip=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV

      # Setup SSH Key
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.instance_ip }} >> ~/.ssh/known_hosts

      - name: Deploy App to EC2
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-automation/terraform/deploy.sh ubuntu@${{ env.instance_ip }}:/home/ubuntu/deploy.sh
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ env.instance_ip }} 'chmod +x ~/deploy.sh && ~/deploy.sh dev'

